name: Testing Github Actions
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test Application
        run: |
          chmod +x test.sh
          ./test.sh
  email_sending:
    runs-on: 'ubuntu-22.04'
    needs: test
    if: ${{ failure() }}
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: sandbox.smtp.mailtrap.io
          server_port: 2525
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: An unexpected error occured!
          body: ${{ github.workflow }} of ${{ github.repository }} has failed
          to: receiver@email.com
          from: sender@email.com
  delivery:
    runs-on: 'ubuntu-22.04'
    needs: test
    steps:
      - name: Apply Changes
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: lesson.lv
          username: teacher 
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          fingerprint: SHA256:oOrrFGkhFJ2fRqqzc+YJvBN2B3fPnvquUpFaL1V1mXA
          script: cd web && git pull